import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import NavBar from "@/components/common/NavBar";
import {NextIntlClientProvider, useMessages} from 'next-intl';

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {

    const messages = useMessages();
  return (
    <html lang={locale}>
      <body  className={nunito.className} >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NavBar />
          {children}
            <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
